package com.example.washmachine.common.exception;

public enum ExceptionId {
    INVALID_POST_BODY_REQUEST_EX,
    INVALID_ACTION_ID_EX,
    INVALID_MACHINE_ID_EX,
    INVALID_WASH_STEP_EX,
    INVALID_WASH_ACTION_STATUS_EX,
    INVALID_ACTION_STATE_EX,
    INVALID_MACHINE_STATE_EX,
    EMPTY_POST_BODY_REQUEST_EX,
    INTERNAL_ERROR
}
